/**
 * File Utility Functions
 * Provides utilities for categorizing files (test files, generated files, etc.)
 */

/**
 * Check if a file path represents a test file
 * Comprehensive test file detection with support for multiple patterns
 *
 * @param filePath - The file path to check
 * @returns true if the file is a test file
 */
export function isTestFile(filePath: string): boolean {
  // Normalize path separators to forward slashes and convert to lowercase
  const lowerPath = filePath.toLowerCase().replace(/\\/g, '/');

  // Common test file patterns
  const testPatterns = [
    // Standard naming conventions
    /\.(test|spec)\.(ts|js|tsx|jsx|mjs|cjs)$/i,

    // Test directories (match at start or after slash)
    /(^|\/)__tests__\//i,
    /(^|\/)__test__\//i,
    /(^|\/)tests?\//i,
    /(^|\/)test\//i,
    /(^|\/)specs?\//i,
    /(^|\/)spec\//i,

    // Framework-specific
    /\.e2e-spec\.(ts|js)$/i, // NestJS e2e tests
    /\.e2e\.(ts|js)$/i,
    /\.integration\.(test|spec)\.(ts|js)$/i,
    /\.unit\.(test|spec)\.(ts|js)$/i,

    // Cypress, Playwright, etc.
    /(^|\/)cypress\//i,
    /(^|\/)e2e\//i,
    /(^|\/)integration\//i,

    // Vitest, Jest config
    /vitest\.config\.(ts|js)$/i,
    /jest\.config\.(ts|js)$/i,
    /jest\.setup\.(ts|js)$/i,

    // Test utils/fixtures
    /(^|\/)test-utils\//i,
    /(^|\/)test-helpers\//i,
    /(^|\/)fixtures\//i,
    /(^|\/)__fixtures__\//i,
    /(^|\/)__mocks__\//i,

    // Additional test patterns (fix for 2,860 test file findings)
    /\.fixture\./i,              // Fixture files
    /(^|\/)mock/i,               // Mock files (case insensitive)
    /(^|\/)examples\//i,         // Example files
    /(^|\/)demos\//i,            // Demo files
    /(^|\/)stubs\//i,            // Stub files
  ];

  return testPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Check if a file path represents a generated file
 * Detects auto-generated code from various tools and frameworks
 *
 * @param filePath - The file path to check
 * @returns true if the file is auto-generated
 */
export function isGeneratedFile(filePath: string): boolean {
  // Normalize path separators to forward slashes and convert to lowercase
  const lowerPath = filePath.toLowerCase().replace(/\\/g, '/');

  // Common generated file patterns
  const generatedPatterns = [
    // Build output directories (match at start or after slash)
    /(^|\/)generated\//i,
    /(^|\/)__generated__\//i,
    /(^|\/)\.next\//i,
    /(^|\/)dist\//i,
    /(^|\/)build\//i,
    /(^|\/)out\//i,
    /(^|\/)output\//i,
    /(^|\/)lib\//i, // Common for compiled libraries

    // Auto-generated file markers
    /@generated/i,
    /autogenerated/i,
    /auto-generated/i,
    /do not edit/i,
    /generated by/i,

    // Common generated file extensions
    /\.generated\.(ts|js|tsx|jsx)$/i,
    /\.g\.(ts|js)$/i,
    /-generated\.(ts|js)$/i,

    // TypeScript declaration files (often generated)
    /\.d\.ts$/i,

    // Protocol buffers, gRPC
    /\.pb\.(ts|js)$/i,
    /_pb\.(ts|js)$/i,
    /\.proto\.ts$/i,

    // GraphQL
    /\.graphql\.ts$/i,
    /__generated__\/.*\.tsx?$/i,

    // Prisma
    /\/\.prisma\//i,
    /@prisma\/client/i,

    // Database migrations
    /\/migrations?\//i,
    /\/migrate\//i,

    // Code generators
    /swagger-codegen/i,
    /openapi-generator/i,

    // Framework-generated files
    /next-env\.d\.ts$/i, // Next.js
    /vite-env\.d\.ts$/i, // Vite
    /react-app-env\.d\.ts$/i, // Create React App

    // Lock files and dependencies
    /package-lock\.json$/i,
    /yarn\.lock$/i,
    /pnpm-lock\.yaml$/i,
    /\/node_modules\//i,

    // Coverage reports
    /\/coverage\//i,
    /\/\.nyc_output\//i,

    // Documentation generated
    /\/docs?\/api\//i,
    /\/typedoc\//i,
  ];

  return generatedPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Get a human-readable category for a file
 * Categorizes files into test, generated, or production code
 *
 * @param filePath - The file path to categorize
 * @returns A category: 'test' | 'generated' | 'production'
 */
export function getFileCategory(filePath: string): 'test' | 'generated' | 'production' {
  if (isTestFile(filePath)) {
    return 'test';
  }
  if (isGeneratedFile(filePath)) {
    return 'generated';
  }
  return 'production';
}

/**
 * Check if a file is a CLI/executable file where console output is expected
 * @param filePath - The file path to check
 * @returns true if file is a CLI/executable
 */
export function isCLIFile(filePath: string): boolean {
  const lowerPath = filePath.toLowerCase().replace(/\\/g, '/');

  const cliPatterns = [
    // CLI directories
    /(^|\/)bin\//i,
    /(^|\/)cli\//i,
    /(^|\/)scripts\//i,
    /(^|\/)tools\//i,

    // CLI file names
    /\/cli\.(ts|js|mjs|cjs)$/i,
    /\/index\.ts$/i, // Often CLI entry point for packages
    /\/main\.(ts|js)$/i,

    // Debug/dev tools
    /(^|\/)debug\//i,
    /(^|\/)dev-tools\//i,
    /(^|\/)dev-server\//i,
  ];

  return cliPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Check if a file is a configuration file
 * @param filePath - The file path to check
 * @returns true if file is a config file
 */
export function isConfigFile(filePath: string): boolean {
  const lowerPath = filePath.toLowerCase().replace(/\\/g, '/');

  const configPatterns = [
    // Config directories
    /(^|\/)config\//i,
    /(^|\/)configs\//i,
    /(^|\/)configuration\//i,

    // Config files
    /\.config\.(ts|js|mjs|cjs)$/i,
    /\.conf\.(ts|js)$/i,
    /\/config\.(ts|js)$/i,
    /\/settings\.(ts|js)$/i,

    // Specific configs
    /tsconfig.*\.json$/i,
    /jest\.config\./i,
    /webpack\.config\./i,
    /vite\.config\./i,
    /rollup\.config\./i,
  ];

  return configPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Check if a file is a migration/seed file
 * @param filePath - The file path to check
 * @returns true if file is a migration/seed file
 */
export function isMigrationFile(filePath: string): boolean {
  const lowerPath = filePath.toLowerCase().replace(/\\/g, '/');

  const migrationPatterns = [
    /(^|\/)migrations?\//i,
    /(^|\/)migrate\//i,
    /(^|\/)seeds?\//i,
    /(^|\/)seeders?\//i,
    /\.migration\.(ts|js)$/i,
    /\.seed\.(ts|js)$/i,
    // Seed files by filename (e.g., routes/seed.js, db/seeder.ts)
    /[/\\]seeds?(?:er)?s?\.(?:ts|js|mjs|cjs)$/i,
  ];

  return migrationPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Check if a file is a build artifact (minified/bundled output from Vite, webpack, Rollup, etc.)
 * These files should not be scanned — their single-letter vars and dense code generate false positives.
 *
 * Detects two patterns:
 *   1. Files in known build-output asset directories (public/assets, dist/assets, .next/static, etc.)
 *   2. Content-hash suffixed filenames — standard bundler output (index-XQYQww37.js, app.a1b2c3d4.js)
 *
 * @param filePath - The file path to check
 * @returns true if the file is a build artifact
 */
export function isBuildArtifact(filePath: string): boolean {
  const normalPath = filePath.replace(/\\/g, '/');

  // Build-output asset directories (Vite, webpack, Next.js, Nuxt, Storybook, etc.)
  const buildAssetDirPatterns = [
    /(^|\/)public\/assets\//i,
    /(^|\/)dist\/assets\//i,
    /(^|\/)build\/static\//i,
    /\/.next\/static\//i,
    /(^|\/)\.nuxt\//i,
    /(^|\/)\.output\//i,
    /(^|\/)storybook-static\//i,
  ];

  if (buildAssetDirPatterns.some(p => p.test(normalPath))) return true;

  // Content-hash suffixed JS/MJS filenames — all major bundlers append a hash:
  //   Vite:    index-XQYQww37.js     (base62, 8 chars)
  //   webpack: main.a1b2c3d4.js      (hex, 8 chars)
  //   Rollup:  chunk-abc12345.mjs    (hex, 8+ chars)
  //   Parcel:  app.1a2b3c4d5e6f.js   (hex, 12 chars)
  const baseName = normalPath.split('/').pop() || '';
  const withoutExt = baseName.replace(/\.(m?js|cjs)$/i, '');
  if (/[-.]([A-Za-z0-9]{7,})$/.test(withoutExt)) return true;

  return false;
}

/**
 * Extract package name from a module specifier
 * Handles scoped packages and subpath imports
 *
 * Examples:
 *   'express' -> 'express'
 *   '@types/node' -> '@types/node'
 *   'lodash/debounce' -> 'lodash'
 *   '@org/package/subpath' -> '@org/package'
 *   'node:fs' -> 'node:fs' (Node.js built-in with protocol)
 *
 * @param moduleName - Module specifier from an import statement
 * @returns Package name
 */
export function extractPackageName(moduleName: string): string {
  // Handle Node.js built-in protocol (node:fs, node:path)
  if (moduleName.startsWith('node:')) {
    return moduleName;
  }

  // Handle scoped packages (@org/package)
  if (moduleName.startsWith('@')) {
    const parts = moduleName.split('/');
    return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : moduleName;
  }

  // Handle subpath imports (package/subpath)
  const firstSlash = moduleName.indexOf('/');
  if (firstSlash > 0) {
    return moduleName.substring(0, firstSlash);
  }

  return moduleName;
}

/**
 * Check if a module specifier is a relative or absolute import
 *
 * @param moduleName - Module specifier
 * @returns true if the import is relative or absolute
 */
export function isRelativeOrAbsoluteImport(moduleName: string): boolean {
  return moduleName.startsWith('.') || moduleName.startsWith('/');
}

/**
 * Check if a module specifier is a path alias or non-npm import.
 * These are never valid npm package names and should never be flagged as
 * hallucinated dependencies.
 *
 * Covers:
 *   @/anything   — Universal @/ alias (Next.js, Vite, Create React App, etc.)
 *   ~/anything   — Nuxt.js, Remix, some custom configs
 *   #anything    — Node.js subpath imports (package.json "imports" field) and #/ aliases
 *   virtual:*    — Vite virtual modules (vite-plugin-pwa, etc.)
 *   *?*          — Vite/webpack query string imports (style.css?inline)
 *
 * @param moduleName - Module specifier
 * @returns true if the import is a path alias or non-npm import
 */
export function isPathAlias(moduleName: string): boolean {
  if (moduleName.startsWith('@/')) return true;   // @/ alias (never a valid npm scope)
  if (moduleName.startsWith('~/')) return true;   // ~/ alias
  if (moduleName.startsWith('#')) return true;    // Node.js subpath imports and #/ aliases
  if (moduleName.startsWith('virtual:')) return true; // Vite virtual modules
  if (moduleName.includes('?')) return true;      // Query string imports (style.css?inline)
  return false;
}

/**
 * Check if a module is a Node.js built-in module
 *
 * @param moduleName - Module name
 * @returns true if it's a Node.js built-in
 */
export function isNodeBuiltin(moduleName: string): boolean {
  // Handle 'node:' protocol
  if (moduleName.startsWith('node:')) {
    return true;
  }

  // List of Node.js built-in modules
  const NODE_BUILTINS = new Set([
    'assert', 'async_hooks', 'buffer', 'child_process', 'cluster', 'console',
    'constants', 'crypto', 'dgram', 'diagnostics_channel', 'dns', 'domain',
    'events', 'fs', 'fs/promises', 'http', 'http2', 'https', 'inspector',
    'module', 'net', 'os', 'path', 'perf_hooks', 'process', 'punycode',
    'querystring', 'readline', 'repl', 'stream', 'stream/promises',
    'string_decoder', 'sys', 'timers', 'timers/promises', 'tls', 'trace_events',
    'tty', 'url', 'util', 'v8', 'vm', 'wasi', 'worker_threads', 'zlib',
    // Additional Node.js modules
    'test', 'sea', 'sqlite',
    // Bun runtime built-in (bun:* protocol and bare 'bun' module)
    'bun', 'bun:test', 'bun:ffi', 'bun:sqlite', 'bun:wrap',
  ]);

  // Bun uses 'bun:' protocol similarly to Node's 'node:'
  if (moduleName.startsWith('bun:')) return true;

  return NODE_BUILTINS.has(moduleName);
}

/**
 * Calculate Shannon entropy of a string
 * Higher values indicate more randomness/complexity
 *
 * @param str - Input string
 * @returns Entropy value (typically 0-8 for text)
 */
export function calculateEntropy(str: string): number {
  if (str.length === 0) return 0;

  const frequencies = new Map<string, number>();

  // Count character frequencies
  for (const char of str) {
    frequencies.set(char, (frequencies.get(char) || 0) + 1);
  }

  // Calculate entropy
  let entropy = 0;
  const len = str.length;

  for (const count of frequencies.values()) {
    const probability = count / len;
    entropy -= probability * Math.log2(probability);
  }

  return entropy;
}

/**
 * Extract a code snippet around a specific line
 * Useful for providing context in error messages
 *
 * @param content - File content
 * @param lineNumber - Target line number (1-indexed)
 * @param contextLines - Number of lines before and after to include
 * @returns Code snippet with line numbers
 */
export function extractContextSnippet(
  content: string,
  lineNumber: number,
  contextLines: number = 2
): string {
  const lines = content.split('\n');
  const startLine = Math.max(0, lineNumber - contextLines - 1);
  const endLine = Math.min(lines.length, lineNumber + contextLines);

  const snippet = lines
    .slice(startLine, endLine)
    .map((line, index) => {
      const actualLineNumber = startLine + index + 1;
      const marker = actualLineNumber === lineNumber ? '>' : ' ';
      return `${marker} ${actualLineNumber.toString().padStart(4)} | ${line}`;
    })
    .join('\n');

  return snippet;
}
