/**
 * File Utility Functions
 * Provides utilities for categorizing files (test files, generated files, etc.)
 */

/**
 * Check if a file path represents a test file
 * Comprehensive test file detection with support for multiple patterns
 *
 * @param filePath - The file path to check
 * @returns true if the file is a test file
 */
export function isTestFile(filePath: string): boolean {
  const lowerPath = filePath.toLowerCase();

  // Common test file patterns
  const testPatterns = [
    // Standard naming conventions
    /\.(test|spec)\.(ts|js|tsx|jsx|mjs|cjs)$/i,

    // Test directories
    /__tests__\//i,
    /\/__test__\//i,
    /\/tests?\//i,
    /\/test\//i,
    /\/specs?\//i,
    /\/spec\//i,

    // Framework-specific
    /\.e2e-spec\.(ts|js)$/i, // NestJS e2e tests
    /\.e2e\.(ts|js)$/i,
    /\.integration\.(test|spec)\.(ts|js)$/i,
    /\.unit\.(test|spec)\.(ts|js)$/i,

    // Cypress, Playwright, etc.
    /\/cypress\//i,
    /\/e2e\//i,
    /\/integration\//i,

    // Vitest, Jest config
    /vitest\.config\.(ts|js)$/i,
    /jest\.config\.(ts|js)$/i,
    /jest\.setup\.(ts|js)$/i,

    // Test utils/fixtures
    /\/test-utils\//i,
    /\/test-helpers\//i,
    /\/fixtures\//i,
    /__fixtures__\//i,
    /__mocks__\//i,
  ];

  return testPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Check if a file path represents a generated file
 * Detects auto-generated code from various tools and frameworks
 *
 * @param filePath - The file path to check
 * @returns true if the file is auto-generated
 */
export function isGeneratedFile(filePath: string): boolean {
  const lowerPath = filePath.toLowerCase();

  // Common generated file patterns
  const generatedPatterns = [
    // Build output directories
    /\/generated\//i,
    /\/__generated__\//i,
    /\/\.next\//i,
    /\/dist\//i,
    /\/build\//i,
    /\/out\//i,
    /\/output\//i,
    /\/lib\//i, // Common for compiled libraries

    // Auto-generated file markers
    /@generated/i,
    /autogenerated/i,
    /auto-generated/i,
    /do not edit/i,
    /generated by/i,

    // Common generated file extensions
    /\.generated\.(ts|js|tsx|jsx)$/i,
    /\.g\.(ts|js)$/i,
    /-generated\.(ts|js)$/i,

    // TypeScript declaration files (often generated)
    /\.d\.ts$/i,

    // Protocol buffers, gRPC
    /\.pb\.(ts|js)$/i,
    /_pb\.(ts|js)$/i,
    /\.proto\.ts$/i,

    // GraphQL
    /\.graphql\.ts$/i,
    /__generated__\/.*\.tsx?$/i,

    // Prisma
    /\/\.prisma\//i,
    /@prisma\/client/i,

    // Database migrations
    /\/migrations?\//i,
    /\/migrate\//i,

    // Code generators
    /swagger-codegen/i,
    /openapi-generator/i,

    // Framework-generated files
    /next-env\.d\.ts$/i, // Next.js
    /vite-env\.d\.ts$/i, // Vite
    /react-app-env\.d\.ts$/i, // Create React App

    // Lock files and dependencies
    /package-lock\.json$/i,
    /yarn\.lock$/i,
    /pnpm-lock\.yaml$/i,
    /\/node_modules\//i,

    // Coverage reports
    /\/coverage\//i,
    /\/\.nyc_output\//i,

    // Documentation generated
    /\/docs?\/api\//i,
    /\/typedoc\//i,
  ];

  return generatedPatterns.some(pattern => pattern.test(lowerPath));
}

/**
 * Get a human-readable category for a file
 * Categorizes files into test, generated, or production code
 *
 * @param filePath - The file path to categorize
 * @returns A category: 'test' | 'generated' | 'production'
 */
export function getFileCategory(filePath: string): 'test' | 'generated' | 'production' {
  if (isTestFile(filePath)) {
    return 'test';
  }
  if (isGeneratedFile(filePath)) {
    return 'generated';
  }
  return 'production';
}

/**
 * Extract package name from a module specifier
 * Handles scoped packages and subpath imports
 *
 * Examples:
 *   'express' -> 'express'
 *   '@types/node' -> '@types/node'
 *   'lodash/debounce' -> 'lodash'
 *   '@org/package/subpath' -> '@org/package'
 *   'node:fs' -> 'node:fs' (Node.js built-in with protocol)
 *
 * @param moduleName - Module specifier from an import statement
 * @returns Package name
 */
export function extractPackageName(moduleName: string): string {
  // Handle Node.js built-in protocol (node:fs, node:path)
  if (moduleName.startsWith('node:')) {
    return moduleName;
  }

  // Handle scoped packages (@org/package)
  if (moduleName.startsWith('@')) {
    const parts = moduleName.split('/');
    return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : moduleName;
  }

  // Handle subpath imports (package/subpath)
  const firstSlash = moduleName.indexOf('/');
  if (firstSlash > 0) {
    return moduleName.substring(0, firstSlash);
  }

  return moduleName;
}

/**
 * Check if a module specifier is a relative or absolute import
 *
 * @param moduleName - Module specifier
 * @returns true if the import is relative or absolute
 */
export function isRelativeOrAbsoluteImport(moduleName: string): boolean {
  return moduleName.startsWith('.') || moduleName.startsWith('/');
}

/**
 * Check if a module is a Node.js built-in module
 *
 * @param moduleName - Module name
 * @returns true if it's a Node.js built-in
 */
export function isNodeBuiltin(moduleName: string): boolean {
  // Handle 'node:' protocol
  if (moduleName.startsWith('node:')) {
    return true;
  }

  // List of Node.js built-in modules
  const NODE_BUILTINS = new Set([
    'assert', 'async_hooks', 'buffer', 'child_process', 'cluster', 'console',
    'constants', 'crypto', 'dgram', 'diagnostics_channel', 'dns', 'domain',
    'events', 'fs', 'fs/promises', 'http', 'http2', 'https', 'inspector',
    'module', 'net', 'os', 'path', 'perf_hooks', 'process', 'punycode',
    'querystring', 'readline', 'repl', 'stream', 'stream/promises',
    'string_decoder', 'sys', 'timers', 'timers/promises', 'tls', 'trace_events',
    'tty', 'url', 'util', 'v8', 'vm', 'wasi', 'worker_threads', 'zlib',
    // Additional Node.js modules
    'test', 'sea', 'sqlite'
  ]);

  return NODE_BUILTINS.has(moduleName);
}

/**
 * Calculate Shannon entropy of a string
 * Higher values indicate more randomness/complexity
 *
 * @param str - Input string
 * @returns Entropy value (typically 0-8 for text)
 */
export function calculateEntropy(str: string): number {
  if (str.length === 0) return 0;

  const frequencies = new Map<string, number>();

  // Count character frequencies
  for (const char of str) {
    frequencies.set(char, (frequencies.get(char) || 0) + 1);
  }

  // Calculate entropy
  let entropy = 0;
  const len = str.length;

  for (const count of frequencies.values()) {
    const probability = count / len;
    entropy -= probability * Math.log2(probability);
  }

  return entropy;
}

/**
 * Extract a code snippet around a specific line
 * Useful for providing context in error messages
 *
 * @param content - File content
 * @param lineNumber - Target line number (1-indexed)
 * @param contextLines - Number of lines before and after to include
 * @returns Code snippet with line numbers
 */
export function extractContextSnippet(
  content: string,
  lineNumber: number,
  contextLines: number = 2
): string {
  const lines = content.split('\n');
  const startLine = Math.max(0, lineNumber - contextLines - 1);
  const endLine = Math.min(lines.length, lineNumber + contextLines);

  const snippet = lines
    .slice(startLine, endLine)
    .map((line, index) => {
      const actualLineNumber = startLine + index + 1;
      const marker = actualLineNumber === lineNumber ? '>' : ' ';
      return `${marker} ${actualLineNumber.toString().padStart(4)} | ${line}`;
    })
    .join('\n');

  return snippet;
}
